# Implementación de Gaussian Naive-Bayes para el proyecto de modelos de autoaprendizaje.
#### Equipo 1: Aurora Álvarez Samano, JosueEstrada Herrera

## Loading Initial Libraries

We will start by loading some initial libraries to load and visualize the dataset.

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

Importarmo los datos que requerimos de nuestro archivo .csv

In [2]:
dataset = pd.read_csv("datos_metodos.csv")

La columna "Nombre", "NUA", "Materia" y "Fecha y hora" las podemos discriminar, ya que no nos proporciona datos como tal para nuestro analisis.

In [4]:
dataset_data = dataset.drop(['Nombre'], axis=1)
dataset_data = dataset_data.drop(['Nua'], axis=1)
dataset_data = dataset_data.drop(['Materia '], axis=1)
dataset_data = dataset_data.drop('Unnamed: 13',1)
dataset_data = dataset_data.drop(['Fecha_hora'], axis=1)

In [5]:
genero= dataset_data.iloc[:, [1]] 
genero = genero.values

for x in range(96):
    if genero[x]=='Hombre':
        genero[x]=1
    elif genero[x]=='Mujer':
        genero[x]=2
    else :
        genero[x]=0

carrera= dataset_data.iloc[:, [2]] 
carrera = carrera.values

for x in range(96):
    if carrera[x]=='LICE':
        carrera[x]=1
    if carrera[x]=='LISC':
        carrera[x]=2
    if carrera[x]=='LGE':
        carrera[x]=3
    if carrera[x]=='LEI':
        carrera[x]=4
        
eleccion= dataset_data.iloc[:, [3]] 
eleccion = eleccion.values

for x in range(96):
    if eleccion[x]=='video':
        eleccion[x]=1
    if eleccion[x]=='pdf':
        eleccion[x]=2
    if eleccion[x]=='audio':
        eleccion[x]=3
    if eleccion[x]=='ejemplo':
        eleccion[x]=4       
        
dataset_data.iloc[:, [1]] = genero
dataset_data.iloc[:, [2]] = carrera
dataset_data.iloc[:, [3]] = eleccion

dataset_data.head()

Semestre  Genero  Carrera  Elección   Tiempo de elección  TiempoVideo  \
0        12       1        1          1                   6     0.584572   
1        12       1        1          2                   8     1.985114   
2        12       1        1          1                   8     1.830355   
3        12       1        1          4                   8     0.000000   
4        12       1        1          1                  11     0.953845   

   TiempoPDF  TiempoAudio  TiempoEjemplo  
0   0.000000     0.696459       1.967743  
1   0.530954     0.000000       2.158200  
2   0.000000     0.000000       0.000000  
3   2.714251     0.000000       2.304171  
4   0.020006     0.301034       0.163310

In [6]:
dataset_data.keys()

Index(['Semestre', 'Genero', 'Carrera', 'Elección ', 'Tiempo de elección',
       'TiempoVideo', 'TiempoPDF', 'TiempoAudio', 'TiempoEjemplo'],
      dtype='object')

In [10]:
from sklearn.model_selection import train_test_split

In [23]:
D = dataset_data.values
x = D[:,0:8]
y = D[:,3]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

#### Defino el algoritmo a utilizar
Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
nb = GaussianNB() # Algoritmo
nb.fit(x_train, y_train)

GaussianNB()

Realizo una predicción

In [27]:
y_pred = nb.predict(x_test)

Veamos la matris de confusión

In [28]:
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[5 0 0 0]
 [0 7 0 0]
 [0 0 2 0]
 [0 0 0 6]]


Calculamos la precisión del modelo

In [33]:
from sklearn.metrics import precision_score


In [34]:
print("Naive Bayes score: ",nb.score(x_test, y_test))

Naive Bayes score:  1.0
